[cerebrium.runtime.custom]
entrypoint = "python telegram_post_bot.py"
port = 8080

[cerebrium.dependencies.pip]
python-telegram-bot = "20.8"
python-dotenv = "1.0.0"
flask = "3.0.0"
jinja2 = "3.1.3"
nest-asyncio = "1.5.8"

[cerebrium.environment]
PYTHONUNBUFFERED = "1"
