version: '3.8'

services:
  telegram-bot:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - PORT=8080
    volumes:
      - ./posts:/app/posts
      - ./bot.log:/app/bot.log
    restart: unless-stopped
    env_file:
      - .env
